-- Auto-generated: add missing legacy columns to schema-farm-v3 tables
-- These columns exist in optimized_schema but not in schema-farm-v3.
-- They're needed to preserve all legacy data during migration.
-- Generated: 2026-04-10T05:51:05.181Z

ALTER TABLE breeding.beast_breeding ADD COLUMN IF NOT EXISTS birth_date DATE NULL;
ALTER TABLE breeding.beast_breeding ADD COLUMN IF NOT EXISTS birth_wght REAL NULL;
ALTER TABLE breeding.beast_breeding ADD COLUMN IF NOT EXISTS genetics SMALLINT NULL;
ALTER TABLE breeding.breeding_dams ADD COLUMN IF NOT EXISTS dam_supplier VARCHAR(50) NULL;
ALTER TABLE breeding.breeding_sires ADD COLUMN IF NOT EXISTS awa_sire_id VARCHAR(50) NULL;
ALTER TABLE breeding.breeding_sires ADD COLUMN IF NOT EXISTS sire_line_id SMALLINT NULL;
ALTER TABLE breeding.breeding_sires ADD COLUMN IF NOT EXISTS sire_supplier VARCHAR(50) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS abattoir_establishment_number INTEGER NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS carc_wght_left REAL NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS carc_wght_right REAL NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS doll_kg_deduction NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS eye_mscle_area REAL NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS meqausmrb SMALLINT NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS meqmsa SMALLINT NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS mscle_colour VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS mscle_score VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS price_doll_kg_left NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS price_doll_kg_right NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_data ADD COLUMN IF NOT EXISTS rcinvoice_date DATE NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ausmarbling SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS bodyno SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS boning_date DATE NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS chainno VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS coldgrader VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS cutcookalgorithmversionnumber VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS date_record_added DATE NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS dentition VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS dest VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ema SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS epbi VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS eqsref VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS failmisc VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS fatcolour VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS fatdistribution VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS feedtype VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS gradecode SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS gradedate DATE NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS grademethod SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS hangmethod VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS hgp VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS hidepullerdamage VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS hotgrader VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS humpcold SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS humphot SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS keyplantchainkillbody VARCHAR(20) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS killdate TIMESTAMPTZ NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS lefthscw REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS leftsidescanttime VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS lointemp REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS lot VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS meatcolour VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS mfv VARCHAR(1) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS msaindex REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS msamarbling SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS msavendordeccount SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS msavendordecserial VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS nlis VARCHAR(16) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS nodaysonfeed SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS nvdserial VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS nvdserialprefix VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS operator VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS opportunityindex REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ossificationcold SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ossificationhot SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ownerproducer VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS p8fat SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ph REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS plant VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS plantboneruntemplate VARCHAR(50) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS plantboningrun VARCHAR(5) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS processorindex REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS rfid VARCHAR(16) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS rib SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS ribfatcold SMALLINT NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS righthscw REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS rightsidescantime VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS rinse VARCHAR(1) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS saleyard VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS saleyardno VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS sex VARCHAR(2) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS species VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS totalhscw REAL NULL;
ALTER TABLE carcase.carcase_datatype2 ADD COLUMN IF NOT EXISTS vendorproducer VARCHAR(10) NULL;
ALTER TABLE carcase.carcase_grades ADD COLUMN IF NOT EXISTS effective_from_date DATE NULL;
ALTER TABLE carcase.carcase_grades ADD COLUMN IF NOT EXISTS price_doll_per_kg NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS from_date DATE;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS qual_grade VARCHAR(5);
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS yg1_price NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS yg2_price NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS yg3_price NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS yg4_price NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_grades_us ADD COLUMN IF NOT EXISTS yg5_price NUMERIC(12,4) NULL;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col1 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col10 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col11 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col12 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col13 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col14 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col15 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col16 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col17 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col18 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col19 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col2 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col20 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col21 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col22 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col23 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col24 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col25 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col3 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col4 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col5 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col6 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col7 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col8 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS col9 TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS error TEXT;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS session_id INTEGER;
ALTER TABLE carcase.carcase_import_data ADD COLUMN IF NOT EXISTS warning TEXT;
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS kill_date_from DATE;
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS kill_date_to DATE;
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS live_or_carc_wght VARCHAR(1);
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS marbling_from REAL;
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS marbling_to REAL;
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS meat_colour_from VARCHAR(2);
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS meat_colour_to VARCHAR(2);
ALTER TABLE carcase.carcase_prices ADD COLUMN IF NOT EXISTS sold_to_id SMALLINT;
ALTER TABLE carcase.marbling_bonus ADD COLUMN IF NOT EXISTS pay_rate_bonus_per_carcase_kg NUMERIC(12,4) NULL;
ALTER TABLE cattle.agistment_transfer_register ADD COLUMN IF NOT EXISTS agistor_tail_tag VARCHAR(10) NULL;
ALTER TABLE cattle.agistment_transfer_register ADD COLUMN IF NOT EXISTS w_bridge_docket VARCHAR(6) NULL;
ALTER TABLE cattle.agistment_transfer_register ADD COLUMN IF NOT EXISTS weight_gain_dollarper_kg NUMERIC(12,4) NULL;
ALTER TABLE cattle.batch_update_log ADD COLUMN IF NOT EXISTS logtext TEXT NULL;
ALTER TABLE cattle.beast_movements ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE cattle.beast_movements ADD COLUMN IF NOT EXISTS movedate DATE NULL;
ALTER TABLE cattle.cattle_dof_dip ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE cattle.cattle_dof_dip ADD COLUMN IF NOT EXISTS date_calculated TIMESTAMPTZ;
ALTER TABLE cattle.cattle_photos ADD COLUMN IF NOT EXISTS beastid INTEGER NULL;
ALTER TABLE cattle.cattle_photos ADD COLUMN IF NOT EXISTS datelastupdated TIMESTAMPTZ NULL;
ALTER TABLE cattle.cattle_processed ADD COLUMN IF NOT EXISTS beastid INTEGER NULL;
ALTER TABLE cattle.cattle_processed ADD COLUMN IF NOT EXISTS draftgate SMALLINT NULL;
ALTER TABLE cattle.cattle_processed ADD COLUMN IF NOT EXISTS saveddate TIMESTAMPTZ NULL;
ALTER TABLE cattle.cattle_processed ADD COLUMN IF NOT EXISTS weighdate TIMESTAMPTZ NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS agentid INTEGER NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS agist_charged_up_to_date DATE NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS background_doll_per_kg NUMERIC(12,4) NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS current_loctype_id SMALLINT NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS customfeedownerid INTEGER NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS died BOOLEAN DEFAULT FALSE;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS dna_or_blood_number VARCHAR(15) NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS ear_tag VARCHAR(8);
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS esi_whold_until TIMESTAMPTZ NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS feedlot_entry_wght REAL NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS growergroupcode SMALLINT NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS nfas_decl_numb VARCHAR(15) NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS nlis_tag_fail_at_induction BOOLEAN NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS pen_number VARCHAR(10) NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS pregtested BOOLEAN NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS purch_lot_no VARCHAR(12) NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS sale_weight REAL NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS start_weight REAL NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS vendorid INTEGER NULL;
ALTER TABLE cattle.cows ADD COLUMN IF NOT EXISTS whold_until TIMESTAMPTZ NULL;
ALTER TABLE cattle.cull_reasons ADD COLUMN IF NOT EXISTS cull_reason VARCHAR(15) NULL;
ALTER TABLE cattle.cull_reasons ADD COLUMN IF NOT EXISTS cull_reason_id SMALLINT;
ALTER TABLE cattle.cull_reasons ADD COLUMN IF NOT EXISTS payrate_per_kg NUMERIC(12,4) NULL;
ALTER TABLE cattle.daily_cattle_inventory ADD COLUMN IF NOT EXISTS accum_month_head_days INTEGER NULL;
ALTER TABLE cattle.market_categories ADD COLUMN IF NOT EXISTS market_cat_id SMALLINT;
ALTER TABLE cattle.market_categories ADD COLUMN IF NOT EXISTS market_category VARCHAR(10);
ALTER TABLE cattle.market_categories ADD COLUMN IF NOT EXISTS predicted_dressing_pcnt REAL NULL;
ALTER TABLE cattle.new_cattle_records_log ADD COLUMN IF NOT EXISTS beastid INTEGER NULL;
ALTER TABLE cattle.new_cattle_records_log ADD COLUMN IF NOT EXISTS mod_ule VARCHAR(100) NULL;
ALTER TABLE cattle.new_cattle_records_log ADD COLUMN IF NOT EXISTS proceedure_name VARCHAR(50) NULL;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS doll_per_head_per_day NUMERIC(12,4);
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS location_code SMALLINT NULL;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_oth TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_pen1 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_pen2 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_pen3 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_pen4 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_cost_per_hd_day_pen5 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_oth TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_pen1 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_pen2 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_pen3 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_pen4 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_gross_value_pen5 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_oth TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_pen1 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_pen2 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_pen3 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_pen4 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS ohead_head_pen5 TEXT;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS period_from DATE;
ALTER TABLE cattle.overhead_application_history ADD COLUMN IF NOT EXISTS period_to DATE;
ALTER TABLE cattle.pen_list_snapshots ADD COLUMN IF NOT EXISTS beast_id INTEGER;
ALTER TABLE cattle.pen_list_snapshots ADD COLUMN IF NOT EXISTS pen TEXT;
ALTER TABLE cattle.purchase_lot_cattle ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE cattle.purchase_lot_cattle ADD COLUMN IF NOT EXISTS numb_head SMALLINT NULL;
ALTER TABLE cattle.purchase_lot_cattle ADD COLUMN IF NOT EXISTS price_cnts_per_kg NUMERIC(12,4) NULL;
ALTER TABLE cattle.purchase_lot_cattle ADD COLUMN IF NOT EXISTS vndr_decl_no VARCHAR(15) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS attachment_contract TEXT NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS attachment_cvd TEXT NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS end_date DATE NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS farmgateprice NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS frght_ton NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS kgs_delivered_since_given_date REAL NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS pay_suppliers_weight BOOLEAN DEFAULT FALSE;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS price_ton NUMERIC(12,4);
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS road_levy_ton NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS rtci_invoice BOOLEAN DEFAULT FALSE;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS specifications VARCHAR(30) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS start_date DATE NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS value_delivered_since_given_date NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS value_incr_per_month NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS vendor_dec VARCHAR(15) NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS wght_contracted REAL NULL;
ALTER TABLE commodity.commodcontracts ADD COLUMN IF NOT EXISTS wght_delivered REAL NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS commod_name VARCHAR(15);
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS description VARCHAR(20) NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS kgs_on_hand REAL NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS mth_open_kgs REAL NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS mth_open_value NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS nonstandard_commodity BOOLEAN NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS shortname VARCHAR(6) NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS superceeded BOOLEAN DEFAULT FALSE;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS tempering_litres_per_kg REAL NULL;
ALTER TABLE commodity.commodities ADD COLUMN IF NOT EXISTS value_on_hand NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS call_weight REAL NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS commod_mast_kgs REAL NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS commod_mast_value NUMERIC(12,4) NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS ctr_id INTEGER;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS feed_load_record_no INTEGER NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS kgs REAL NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS month_end_process BOOLEAN DEFAULT FALSE;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS reason_code SMALLINT NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS ref_no VARCHAR(8);
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS staffid SMALLINT NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS tempered_weight_fed_kgs REAL NULL;
ALTER TABLE commodity.commodtrans ADD COLUMN IF NOT EXISTS value NUMERIC(12,4) NULL;
ALTER TABLE commodity.period_stocks_closing_balance ADD COLUMN IF NOT EXISTS commodity_name VARCHAR(15) NULL;
ALTER TABLE commodity.period_stocks_closing_balance ADD COLUMN IF NOT EXISTS stock_tons_weight REAL;
ALTER TABLE commodity.period_stocks_closing_balance ADD COLUMN IF NOT EXISTS stock_value NUMERIC(12,4);
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS acn VARCHAR(15) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS address VARCHAR(100) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS apply_feed_as_dm_kgs BOOLEAN DEFAULT FALSE;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS currentnumberusers SMALLINT NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS data_collector_scales_type VARCHAR(30) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS date_db_last_updated TIMESTAMPTZ NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS date_last_feedtrans_compression TIMESTAMPTZ NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS dflt_wg_per_day REAL NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS digistar_datakey BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS digistar_datalink BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS key VARCHAR(20) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS last_ohead_application TIMESTAMPTZ NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS nsa_client BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS nsa_cust_id VARCHAR(8) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS nsa_email VARCHAR(50) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS padd_tail_tag VARCHAR(10) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS password_complexity BOOLEAN DEFAULT FALSE;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS rfid_space_removed BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS scales_file_folder VARCHAR(100) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS titration_feeding BOOLEAN DEFAULT FALSE;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS units_per_ton INTEGER NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS user_logon BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS usertailtag VARCHAR(10) NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS v11_database BOOLEAN NULL;
ALTER TABLE contacts.company ADD COLUMN IF NOT EXISTS weight_units VARCHAR(4) NULL;
ALTER TABLE contacts.company_settings ADD COLUMN IF NOT EXISTS datecreated TIMESTAMPTZ NULL;
ALTER TABLE contacts.company_settings ADD COLUMN IF NOT EXISTS datemodified TIMESTAMPTZ NULL;
ALTER TABLE contacts.company_settings ADD COLUMN IF NOT EXISTS modulename VARCHAR(100);
ALTER TABLE contacts.company_settings ADD COLUMN IF NOT EXISTS settingname VARCHAR(100);
ALTER TABLE contacts.company_settings ADD COLUMN IF NOT EXISTS settingvalue VARCHAR(255) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS abattoir_establishment_number TEXT NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS agistment_feedlot_rate NUMERIC(12,4) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS agistment_paddock_rate NUMERIC(12,4) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS bank_ac VARCHAR(12) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS brand_drawing_filename VARCHAR(255) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS contact_type SMALLINT NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS days_invoice_due SMALLINT NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS fax_no VARCHAR(15) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS invoice_careof VARCHAR(50) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS mobile_no VARCHAR(15) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS salutation VARCHAR(5) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS tail_tag_no VARCHAR(10) NULL;
ALTER TABLE contacts.contacts ADD COLUMN IF NOT EXISTS tel_no VARCHAR(15) NULL;
ALTER TABLE contacts.contacttypes ADD COLUMN IF NOT EXISTS description VARCHAR(70) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS batchbox VARCHAR(3) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS c15 VARCHAR(6) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS call_wght INTEGER NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS commod_pen VARCHAR(6) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS date_format VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS done VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS driver_id SMALLINT NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS head_count INTEGER NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS ingred_pen VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS last_feed_for_pen VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS mix_time VARCHAR(6) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS time_done VARCHAR(5) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS trck_mill_loaded VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS truck VARCHAR(6) NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS truck_weight_now INTEGER NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS wght_delivered INTEGER NULL;
ALTER TABLE digistar.digistar_data_history ADD COLUMN IF NOT EXISTS zone VARCHAR(1) NULL;
ALTER TABLE digistar.digistar_users ADD COLUMN IF NOT EXISTS user_id SMALLINT NULL;
ALTER TABLE digistar.digistar_users ADD COLUMN IF NOT EXISTS username VARCHAR(30) NULL;
ALTER TABLE feed.bunk_code_desc ADD COLUMN IF NOT EXISTS bunk_code SMALLINT NULL;
ALTER TABLE feed.bunk_code_desc ADD COLUMN IF NOT EXISTS kgs_head_adj REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS avg_kgs_fed_today REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS bk_id INTEGER;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS bunk_reading VARCHAR(2) NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS date_checked DATE NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS early_bunk_reading VARCHAR(2) NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS early_bunk_reading2 VARCHAR(2) NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS feed_alloc REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS kgs_feed_remaining SMALLINT NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS mmec_incr_if_slick REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS mmec_kgs_head REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS mmec_maxfeed REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS mmec_ration REAL NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS mob_name VARCHAR(8) NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS no_head SMALLINT NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS notes VARCHAR(250) NULL;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS pf_kgs_head_change BOOLEAN DEFAULT FALSE;
ALTER TABLE feed.bunk_readings ADD COLUMN IF NOT EXISTS shovel_bunk BOOLEAN NULL;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS date_applied TIMESTAMPTZ;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS dollars_applied NUMERIC(12,4);
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS dollars_not_applied NUMERIC(12,4);
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS est_curr_wght NUMERIC(12,4);
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS head INTEGER;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS head_expected INTEGER;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS kgs_feed_as_fed NUMERIC(12,4);
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS kgs_not_applied NUMERIC(12,4);
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS pen_number TEXT;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS ration_name TEXT;
ALTER TABLE feed.cattle_feed_updates ADD COLUMN IF NOT EXISTS run_number INTEGER;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS feed_date DATE NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS pen_number_id SMALLINT NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_code_feed1 SMALLINT NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_code_feed2 SMALLINT NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_code_feed3 SMALLINT NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_name_feed1 VARCHAR(8) NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_name_feed2 VARCHAR(8) NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_name_feed3 VARCHAR(8) NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_pcnt_feed1 REAL NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_pcnt_feed2 REAL NULL;
ALTER TABLE feed.dual_ration_feeding ADD COLUMN IF NOT EXISTS ration_pcnt_feed3 REAL NULL;
ALTER TABLE feed.feed_month_end_date ADD COLUMN IF NOT EXISTS current_monthend_date DATE NULL;
ALTER TABLE feed.feed_month_end_date ADD COLUMN IF NOT EXISTS current_monthstart_date DATE NULL;
ALTER TABLE feed.feeddb_pens_file ADD COLUMN IF NOT EXISTS current_exit_pen BOOLEAN NULL;
ALTER TABLE feed.feeddb_pens_file ADD COLUMN IF NOT EXISTS include_in_pen_list BOOLEAN NULL;
ALTER TABLE feed.feeddb_pens_file ADD COLUMN IF NOT EXISTS ispaddock BOOLEAN NULL;
ALTER TABLE feed.feeding_details ADD COLUMN IF NOT EXISTS bunk_codes_total SMALLINT NULL;
ALTER TABLE feed.feeding_details ADD COLUMN IF NOT EXISTS feeding_regimen_id SMALLINT NULL;
ALTER TABLE feed.feeding_details ADD COLUMN IF NOT EXISTS kgs_head_adj REAL NULL;
ALTER TABLE feed.feeding_details ADD COLUMN IF NOT EXISTS rec_id INTEGER;
ALTER TABLE feed.feeding_regimens ADD COLUMN IF NOT EXISTS accum_bunkcode_days SMALLINT NULL;
ALTER TABLE feed.feeding_regimens ADD COLUMN IF NOT EXISTS consump_per_head_from REAL NULL;
ALTER TABLE feed.feeding_regimens ADD COLUMN IF NOT EXISTS consump_per_head_to REAL NULL;
ALTER TABLE feed.feeding_regimens ADD COLUMN IF NOT EXISTS feeding_regimen_id SMALLINT NULL;
ALTER TABLE feed.feeding_regimens ADD COLUMN IF NOT EXISTS ration_type SMALLINT;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS first_pen_fed VARCHAR(10) NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS first_pen_fed_time TIMESTAMPTZ NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS last_pen_fed VARCHAR(10) NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS last_pen_fed_time TIMESTAMPTZ NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS ten_day_avg_end_time TIMESTAMPTZ NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS ten_day_avg_start_time TIMESTAMPTZ NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS tons_per_hour REAL NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS total_feeding_time TIMESTAMPTZ NULL;
ALTER TABLE feed.feeding_time_data ADD COLUMN IF NOT EXISTS total_tons_fed REAL NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS cycle VARCHAR(1) NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS first_pen_fed VARCHAR(10) NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS first_pen_feed_time VARCHAR(5) NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS last_pen_fed VARCHAR(10) NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS last_pen_feed_time VARCHAR(5) NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS numberpens INTEGER NULL;
ALTER TABLE feed.feeding_time_taken_by_ration_type ADD COLUMN IF NOT EXISTS sumofwght_delivered INTEGER NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS cattle_data_entry BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS cattle_deletes BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS cattle_lookup_tables BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS cattle_reports BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS cattle_utilities BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS feed_system_data_entry BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS feed_system_reports BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS feed_system_utilities BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS finish_date DATE NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS firstname VARCHAR(20) NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS job_desc VARCHAR(50) NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS password_hash VARCHAR(72) NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS password_last_changed_date TIMESTAMPTZ NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS pen_rider BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS pl_reports_allowed BOOLEAN NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS start_date DATE NULL;
ALTER TABLE feed.feedlot_staff ADD COLUMN IF NOT EXISTS surname VARCHAR(20);
ALTER TABLE feed.instrument_calibration_tests ADD COLUMN IF NOT EXISTS data_applied_to_instruments BOOLEAN NULL;
ALTER TABLE feed.instrument_calibration_tests ADD COLUMN IF NOT EXISTS instrument_name VARCHAR(30);
ALTER TABLE feed.instrument_calibration_tests ADD COLUMN IF NOT EXISTS test_date DATE;
ALTER TABLE feed.instrument_calibration_tests ADD COLUMN IF NOT EXISTS test_notes VARCHAR(100);
ALTER TABLE feed.instrument_calibration_tests ADD COLUMN IF NOT EXISTS testing_method VARCHAR(50);
ALTER TABLE feed.instruments_needing_calibration ADD COLUMN IF NOT EXISTS date_last_tested DATE;
ALTER TABLE feed.instruments_needing_calibration ADD COLUMN IF NOT EXISTS inactive BOOLEAN NULL;
ALTER TABLE feed.instruments_needing_calibration ADD COLUMN IF NOT EXISTS instrument_name VARCHAR(30);
ALTER TABLE feed.instruments_needing_calibration ADD COLUMN IF NOT EXISTS testing_frequency VARCHAR(10);
ALTER TABLE feed.instruments_needing_calibration ADD COLUMN IF NOT EXISTS testing_method VARCHAR(50) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS avg_current_wght REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS bunk_call REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS cp_percentage_dry REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS dry_matter_percent REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS effective_from_date DATE NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS feed_last_24_hrs REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS fourteen_day_avg REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS headcount SMALLINT NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS implanted VARCHAR(1) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS lot_number VARCHAR(12) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS me_mj_kg_dry REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS mktcat VARCHAR(10) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS mktsubcat VARCHAR(10) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS neg_dry REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS nem_dry REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS pen_name VARCHAR(10) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS ration_description VARCHAR(10) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS ration_id SMALLINT NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS ration_short_name VARCHAR(10) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS seven_day_avg REAL NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS sex VARCHAR(3) NULL;
ALTER TABLE feed.nsa_bunk_data ADD COLUMN IF NOT EXISTS thedate TIMESTAMPTZ;
ALTER TABLE feed.paddock_feeding ADD COLUMN IF NOT EXISTS beastid INTEGER NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS comments VARCHAR(100) NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS date_bunk_cleaned DATE NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS date_pen_cleaned DATE NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS date_water_cleaned DATE NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS days_between_cleaning SMALLINT NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS days_since_bunk_clean SMALLINT NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS days_since_pen_clean SMALLINT NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS days_since_water_cleaned SMALLINT NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS pen_ground_type VARCHAR(15) NULL;
ALTER TABLE feed.pen_and_bunk_cleaning ADD COLUMN IF NOT EXISTS pen_type VARCHAR(15) NULL;
ALTER TABLE feed.pen_feeding_order_params ADD COLUMN IF NOT EXISTS extra_feed_pctallowed SMALLINT NULL;
ALTER TABLE feed.pen_feeding_order_params ADD COLUMN IF NOT EXISTS feed_system_b_trigger SMALLINT NULL;
ALTER TABLE feed.pen_feeding_order_params ADD COLUMN IF NOT EXISTS truck_size INTEGER NULL;
ALTER TABLE feed.pen_feeding_order_params ADD COLUMN IF NOT EXISTS truck_volume REAL NULL;
ALTER TABLE feed.pen_feeding_order_params ADD COLUMN IF NOT EXISTS truckname VARCHAR(6) NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS batch_number SMALLINT NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS call_wght REAL NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS feed_weight REAL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS load_numb_for_day SMALLINT;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS load_recid INTEGER;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS mob_name VARCHAR(8) NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS number_cattle SMALLINT;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS postpone_feed_application BOOLEAN NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS ration_value_per_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS system_user_id SMALLINT NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS time_fed VARCHAR(5) NULL;
ALTER TABLE feed.penfeedsdata ADD COLUMN IF NOT EXISTS truck_no VARCHAR(6);
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS beastsex VARCHAR(1);
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS bumpifslick_constant REAL NULL;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS consumpt_avg_constant REAL NULL;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS consumpt_max_constant REAL NULL;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS minnem_constant REAL NULL;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS minnem_power_raised REAL NULL;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS rationcode SMALLINT;
ALTER TABLE feed.ration_calc_constants ADD COLUMN IF NOT EXISTS rationname VARCHAR(15);
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS current_value_kg NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS custom_feed_charge_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS custom_feed_markup_doll_per_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS custom_pcnt_markup REAL NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS date_last_modified DATE NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS date_ration_created DATE NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS delivered_to_bunk_cost_per_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS interest_cost_per_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS liquids_premix_ration BOOLEAN NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS micro_nutrient_cost_per_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS minimum_ration_value_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS mixing_time VARCHAR(6) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS nem_kg REAL NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS pcnt_feedweight_tolerance REAL NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS ration_colour VARCHAR(15) NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS ration_density REAL NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS stationary_mixer BOOLEAN NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS superceeded BOOLEAN DEFAULT FALSE;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS withhold_days INTEGER NULL;
ALTER TABLE feed.ration_descriptions ADD COLUMN IF NOT EXISTS zonename VARCHAR(3) NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS liquid_ration_component BOOLEAN NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS loading_seq SMALLINT NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS rec_id INTEGER;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS tolerance_kgs SMALLINT NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS total_callweight_today_cycle1 REAL NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS total_callweight_today_cycle2 REAL NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS total_callweight_today_cycle3 REAL NULL;
ALTER TABLE feed.ration_recipe_records ADD COLUMN IF NOT EXISTS total_callweight_today_cycle4 REAL NULL;
ALTER TABLE feed.ration_regimes ADD COLUMN IF NOT EXISTS am_ration VARCHAR(10) NULL;
ALTER TABLE feed.ration_regimes ADD COLUMN IF NOT EXISTS am_ration_code SMALLINT NULL;
ALTER TABLE feed.ration_regimes ADD COLUMN IF NOT EXISTS feed_date DATE NULL;
ALTER TABLE feed.ration_regimes ADD COLUMN IF NOT EXISTS pm_ration VARCHAR(10) NULL;
ALTER TABLE feed.ration_regimes ADD COLUMN IF NOT EXISTS pm_ration_code SMALLINT NULL;
ALTER TABLE feed.ration_types ADD COLUMN IF NOT EXISTS group_name VARCHAR(15) NULL;
ALTER TABLE feed.ration_types ADD COLUMN IF NOT EXISTS notes VARCHAR(50) NULL;
ALTER TABLE feed.ration_types ADD COLUMN IF NOT EXISTS ration_type VARCHAR(15);
ALTER TABLE feed.rations ADD COLUMN IF NOT EXISTS custom_feed_charge_ton NUMERIC(12,4) NULL;
ALTER TABLE feed.rations ADD COLUMN IF NOT EXISTS notes VARCHAR(50) NULL;
ALTER TABLE feed.rations ADD COLUMN IF NOT EXISTS ration_name VARCHAR(10);
ALTER TABLE feed.rations ADD COLUMN IF NOT EXISTS valueperton NUMERIC(12,4) NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS adg_expected REAL NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS date_defined DATE NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS end_day_number SMALLINT;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_code_feed1 SMALLINT NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_code_feed2 SMALLINT NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_code_feed3 SMALLINT NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_code_feed4 SMALLINT NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_name_feed1 VARCHAR(10) NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_name_feed2 VARCHAR(10) NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_name_feed3 VARCHAR(10) NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_name_feed4 VARCHAR(10) NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_pcnt_feed1 REAL NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_pcnt_feed2 REAL NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_pcnt_feed3 REAL NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS ration_pcnt_feed4 REAL NULL;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS start_day_number SMALLINT;
ALTER TABLE feed.titration_ration_regimes ADD COLUMN IF NOT EXISTS titration_regime_name VARCHAR(15);
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS born_on_vend_prop BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS chem_res_restriction BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS endosulfan_date DATE NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS endosulfan_exposure BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS fed_animal_fats BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS owned_2_6_months BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS owned_6_12_months BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS owned_gt_12_months BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS owned_lt_2months BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS qa_program_details VARCHAR(50) NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS withholding_for_drugs BOOLEAN NULL;
ALTER TABLE feed.vendor_declarations ADD COLUMN IF NOT EXISTS withholding_for_feed BOOLEAN NULL;
ALTER TABLE finance.beast_accumed_feed_by_commodity ADD COLUMN IF NOT EXISTS accumed_cost NUMERIC(12,4);
ALTER TABLE finance.beast_accumed_feed_by_commodity ADD COLUMN IF NOT EXISTS accumed_custfeed_charge NUMERIC(12,4);
ALTER TABLE finance.beast_accumed_feed_by_commodity ADD COLUMN IF NOT EXISTS accumed_kgs REAL;
ALTER TABLE finance.beast_accumed_feed_by_commodity ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE finance.beast_accumed_feed_by_commodity ADD COLUMN IF NOT EXISTS date_last_updated DATE;
ALTER TABLE finance.cost_codes ADD COLUMN IF NOT EXISTS rev_exp VARCHAR(1);
ALTER TABLE finance.costs ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE finance.costs ADD COLUMN IF NOT EXISTS extended_revexp NUMERIC(12,4) NULL;
ALTER TABLE finance.costs ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE finance.costs ADD COLUMN IF NOT EXISTS rev_exp_per_unit NUMERIC(12,4) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS custom_feed_charge_ton NUMERIC(12,4) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS extended_revexp NUMERIC(12,4) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS forced_application BOOLEAN NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS paddock_feed BOOLEAN DEFAULT FALSE;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS penwhenfed VARCHAR(10) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS ration VARCHAR(10) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS rev_exp_per_unit NUMERIC(12,4) NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS units REAL NULL;
ALTER TABLE finance.costs_feed_detail ADD COLUMN IF NOT EXISTS units_drymatter REAL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS agist_days_for_period INTEGER NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS agist_days_to_date INTEGER NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS cattle_owner_details VARCHAR(150) NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS cattle_owner_id SMALLINT NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS comments VARCHAR(100) NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS days_invoice_due SMALLINT NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS drugs_costs_in_period NUMERIC(12,4);
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS drugs_costs_to_date NUMERIC(12,4);
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS dry_kgs_feed_period REAL NULL;
ALTER TABLE finance.custfeed_lot_summary ADD COLUMN IF NOT EXISTS dry_kgs_feed_to_date REAL NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS group_no SMALLINT NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS intake_kgs INTEGER NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS month_end_date DATE NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS prime_cost NUMERIC(12,4) NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS rec_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS section_name VARCHAR(30) NULL;
ALTER TABLE finance.monthly_fl_intake_cost ADD COLUMN IF NOT EXISTS seq_no SMALLINT NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS basicfeeding REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS basicpackage REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS countrycode SMALLINT;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS crushsideproc REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS feedcommodssystem REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS priceasatdate DATE NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS priceperthousandhead REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS vetrecords REAL NULL;
ALTER TABLE finance.packagecosts ADD COLUMN IF NOT EXISTS vetreporting REAL NULL;
ALTER TABLE finance.price_adjustment_by_weight_range ADD COLUMN IF NOT EXISTS applied_to_cattle_pricing BOOLEAN NULL;
ALTER TABLE finance.price_adjustment_by_weight_range ADD COLUMN IF NOT EXISTS dollars_per_kg_adjustment NUMERIC(12,4) NULL;
ALTER TABLE finance.price_adjustment_by_weight_range ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE finance.price_adjustment_by_weight_range ADD COLUMN IF NOT EXISTS weight_from INTEGER NULL;
ALTER TABLE finance.price_adjustment_by_weight_range ADD COLUMN IF NOT EXISTS weight_to INTEGER NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS criteria VARCHAR(20);
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS doll_per_kg_deductn NUMERIC(12,4) NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS doll_per_kg_mrb_bonus NUMERIC(12,4) NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS doll_per_kg_paid NUMERIC(12,4) NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS mkt_catgry VARCHAR(20);
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS range_from VARCHAR(4) NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS range_to VARCHAR(4) NULL;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS row_sequence SMALLINT;
ALTER TABLE finance.rcti_payment_grid ADD COLUMN IF NOT EXISTS sex VARCHAR(1);
ALTER TABLE finance.rv_rcti_data ADD COLUMN IF NOT EXISTS cost NUMERIC(12,4) NULL;
ALTER TABLE finance.rv_rcti_data ADD COLUMN IF NOT EXISTS cull_reason VARCHAR(20) NULL;
ALTER TABLE finance.rv_rcti_data ADD COLUMN IF NOT EXISTS head SMALLINT NULL;
ALTER TABLE finance.rv_rcti_data ADD COLUMN IF NOT EXISTS notes VARCHAR(50) NULL;
ALTER TABLE finance.rv_rcti_data ADD COLUMN IF NOT EXISTS weight REAL NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS animal_grade VARCHAR(3) NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS date_paid DATE NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS date_purchased DATE NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS payment_status VARCHAR(9) NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS sale_yard_or_paddock TEXT NULL;
ALTER TABLE finance.tandr_buying_details ADD COLUMN IF NOT EXISTS sale_yard_pen VARCHAR(5) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS account_code VARCHAR(4) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS address VARCHAR(100) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS bank_ac_name VARCHAR(50) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS bank_ac_number VARCHAR(16) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS bank_bsb VARCHAR(10) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS company_name VARCHAR(50) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS default_days_invoice_due SMALLINT NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS fax_number VARCHAR(16) NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS gst_rate REAL NULL;
ALTER TABLE finance.tax_invoice_bank_details ADD COLUMN IF NOT EXISTS telephone VARCHAR(16) NULL;
ALTER TABLE finance.tr_payment_breed_adjust ADD COLUMN IF NOT EXISTS breedname VARCHAR(20) NULL;
ALTER TABLE finance.tr_payment_breed_adjust ADD COLUMN IF NOT EXISTS price_per_kg_adjust NUMERIC(12,4) NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS "0_to_2_teeth" REAL NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS "3_to_4_teeth" REAL NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS "5_to_8_teeth" REAL NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS valid_from_date DATE NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS vendor_bred_adjust REAL NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS wght_from SMALLINT NULL;
ALTER TABLE finance.tr_payment_rates ADD COLUMN IF NOT EXISTS wght_to SMALLINT NULL;
ALTER TABLE health.autopsy_records ADD COLUMN IF NOT EXISTS tarchea_fluid BOOLEAN DEFAULT FALSE;
ALTER TABLE health.chemical_inventory ADD COLUMN IF NOT EXISTS expirydate DATE NULL;
ALTER TABLE health.diseases ADD COLUMN IF NOT EXISTS bodysystemid SMALLINT NULL;
ALTER TABLE health.diseases ADD COLUMN IF NOT EXISTS disease_id SMALLINT;
ALTER TABLE health.diseases ADD COLUMN IF NOT EXISTS disease_name VARCHAR(25);
ALTER TABLE health.diseases ADD COLUMN IF NOT EXISTS no_longer_used BOOLEAN DEFAULT FALSE;
ALTER TABLE health.diseases ADD COLUMN IF NOT EXISTS penapp_disease_name VARCHAR(25) NULL;
ALTER TABLE health.drug_disposals ADD COLUMN IF NOT EXISTS date_disposed DATE;
ALTER TABLE health.drug_disposals ADD COLUMN IF NOT EXISTS disposal_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE health.drug_disposals ADD COLUMN IF NOT EXISTS drugid INTEGER NULL;
ALTER TABLE health.drug_disposals ADD COLUMN IF NOT EXISTS number_disposed REAL NULL NULL;
ALTER TABLE health.drug_inventory_line_items ADD COLUMN IF NOT EXISTS boxbottles_onhand REAL NULL;
ALTER TABLE health.drug_inventory_line_items ADD COLUMN IF NOT EXISTS drugid SMALLINT NULL NULL;
ALTER TABLE health.drug_inventory_line_items ADD COLUMN IF NOT EXISTS units_per_boxorbottle INTEGER NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS antibiotic BOOLEAN NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS current_batch_numb VARCHAR(15) NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS drug_id SMALLINT;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS drug_name VARCHAR(20);
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS hgp BOOLEAN NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS inactive BOOLEAN NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS reorder_soh_units_trigger INTEGER NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS units VARCHAR(10) NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS units_per_boxorbottle INTEGER NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS withhold_days_1 SMALLINT NULL;
ALTER TABLE health.drugs ADD COLUMN IF NOT EXISTS withhold_days_esi SMALLINT NULL;
ALTER TABLE health.drugs_given ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE health.drugs_given ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE health.drugs_purchased ADD COLUMN IF NOT EXISTS drugid SMALLINT NULL;
ALTER TABLE health.mort_morb_triggers ADD COLUMN IF NOT EXISTS tablename VARCHAR(10);
ALTER TABLE health.sick_beast_records ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE health.sick_beast_temperatures ADD COLUMN IF NOT EXISTS beastid INTEGER NULL;
ALTER TABLE health.treatment_regimes ADD COLUMN IF NOT EXISTS day_numb SMALLINT NULL;
ALTER TABLE health.treatment_regimes ADD COLUMN IF NOT EXISTS diseaseid SMALLINT NULL;
ALTER TABLE health.treatment_regimes ADD COLUMN IF NOT EXISTS dosebyweight BOOLEAN NULL;
ALTER TABLE health.treatment_regimes ADD COLUMN IF NOT EXISTS drug_name VARCHAR(20) NULL;
ALTER TABLE operations.archiving_log ADD COLUMN IF NOT EXISTS date_done DATE NULL;
ALTER TABLE operations.archiving_log ADD COLUMN IF NOT EXISTS record_selection TEXT NULL;
ALTER TABLE operations.archiving_log ADD COLUMN IF NOT EXISTS reverse_archive BOOLEAN NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS bunk_volume REAL NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS changedate TIMESTAMPTZ NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS changetype CHAR(15) NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS date_last_cleaned DATE NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS dateenteredfeedlot TIMESTAMPTZ NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS excel_cell VARCHAR(5) NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS exclude_from_feed_generation BOOLEAN NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS expected_wg_day REAL NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS feeding_system SMALLINT NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS inc_in_plateau_feed BOOLEAN DEFAULT FALSE;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS ispaddock BOOLEAN NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS kgs_head REAL NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS logid INTEGER;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS mob_name VARCHAR(8) NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS numb_head SMALLINT;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS pen_name VARCHAR(10);
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS ration_code INTEGER NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS ration_code_pm SMALLINT NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS titration_regime VARCHAR(15) NULL;
ALTER TABLE pen.log_pens_file ADD COLUMN IF NOT EXISTS titration_regime_start_date TIMESTAMPTZ NULL;
ALTER TABLE pen.pen_cleaning_dates ADD COLUMN IF NOT EXISTS date_cleaned DATE;
ALTER TABLE pen.pen_cleaning_dates ADD COLUMN IF NOT EXISTS pen_name VARCHAR(10);
ALTER TABLE pen.pen_print_order ADD COLUMN IF NOT EXISTS pen_name VARCHAR(10) NULL;
ALTER TABLE pen.pen_print_order ADD COLUMN IF NOT EXISTS printorder SMALLINT NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_121_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_121_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_46_120_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_46_120_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_gt_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_gt_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_le_45_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_le_45_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_total_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS death_alloc_total_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_121_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_121_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_46_120_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_46_120_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_gt_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_gt_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_le_45_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_le_45_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_total_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS pulls_totals_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_121_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_121_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_46_120_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_46_120_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_gt_200_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_gt_200_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_lt_45_dof_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_pcnt_lt_45_dof_to INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_totals_from INTEGER NULL;
ALTER TABLE pen.pen_rider_tolerances ADD COLUMN IF NOT EXISTS treat_success_totals_to INTEGER NULL;
ALTER TABLE pen.penlaneorder ADD COLUMN IF NOT EXISTS laneorder SMALLINT NULL;
ALTER TABLE pen.penlaneorder ADD COLUMN IF NOT EXISTS pen_name VARCHAR(10);
ALTER TABLE pen.penlaneorder ADD COLUMN IF NOT EXISTS zone_number SMALLINT NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS bunk_volume REAL NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS date_last_cleaned DATE NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS dateenteredfeedlot TIMESTAMPTZ NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS excel_cell VARCHAR(5) NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS exclude_from_feed_generation BOOLEAN NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS expected_wg_day REAL NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS feeding_system SMALLINT NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS inc_in_plateau_feed BOOLEAN DEFAULT FALSE;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS ispaddock BOOLEAN NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS kgs_head REAL NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS numb_head SMALLINT;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS ration_code INTEGER NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS ration_code_pm SMALLINT NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS titration_regime VARCHAR(15) NULL;
ALTER TABLE pen.pens_file ADD COLUMN IF NOT EXISTS titration_regime_start_date TIMESTAMPTZ NULL;
ALTER TABLE pen.pensfed ADD COLUMN IF NOT EXISTS feed_date DATE;
ALTER TABLE pen.pensfed ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE pen.penshistory ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE pen.penshistory ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE pen.penshistory ADD COLUMN IF NOT EXISTS pen VARCHAR(10);
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS agent VARCHAR(30) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS agist_rate_per_day NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS agistor_code SMALLINT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS applied_to_cattle_file BOOLEAN DEFAULT FALSE;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS buyer VARCHAR(30) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS buyer_commiss_per_head REAL NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS buying_fee NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS cattle_freight_cost NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS cost_of_cattle NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS custom_feed_lot BOOLEAN DEFAULT FALSE;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS date_cattle_inv_approved DATE NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS date_frght_inv_approved DATE NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS feed_charge_per_ton NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS finance_rate VARCHAR(10) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS growergroupcode SMALLINT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS invoice_amount NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS is_financed BOOLEAN DEFAULT FALSE;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS lot_notes TEXT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS marbling_bonus_lot BOOLEAN NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS number_head SMALLINT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS nvd_scan_filename VARCHAR(255) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS optional_scan_filename1 VARCHAR(255) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS optional_scan_filename2 VARCHAR(255) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS other_buying_costs NUMERIC(12,4) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS purchase_region SMALLINT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS risk_factor SMALLINT NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS total_weight REAL NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS wbridge_docket VARCHAR(6) NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS weigh_bridge_weight REAL NULL;
ALTER TABLE purchasing.purchase_lots ADD COLUMN IF NOT EXISTS weigh_ticket_scan_filename VARCHAR(255) NULL;
ALTER TABLE purchasing.purchase_totals ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE purchasing.purchase_totals ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE purchasing.purchase_totals ADD COLUMN IF NOT EXISTS tail_tag VARCHAR(10);
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS month_end_date DATE;
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS soh_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS soh_head INTEGER NULL;
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS soh_oheads_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS soh_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.month_end_stockonhand ADD COLUMN IF NOT EXISTS total_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_adjustment_ob ADD COLUMN IF NOT EXISTS feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_adjustment_ob ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE reporting.monthly_adjustment_ob ADD COLUMN IF NOT EXISTS month_end_date DATE;
ALTER TABLE reporting.monthly_adjustment_ob ADD COLUMN IF NOT EXISTS other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_adjustment_ob ADD COLUMN IF NOT EXISTS prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS month_end_date DATE NULL;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS rec_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS section_name VARCHAR(30) NULL;
ALTER TABLE reporting.monthly_agistor_movements ADD COLUMN IF NOT EXISTS seq_no SMALLINT NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS agist_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS agist_head INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS agist_kgs INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS agist_other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS agist_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS culls_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS culls_head INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS culls_kgs INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS culls_other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS culls_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS cust_feedlot_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS cust_feedlot_head INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS cust_feedlot_kgs INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS cust_feedlot_other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS cust_feedlot_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS feed_lot_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS feed_lot_head INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS feed_lot_other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS feed_lot_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS feedlot_kgs INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS month_end_date DATE NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rec_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rv_agist_feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rv_agist_head INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rv_agist_kgs INTEGER NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rv_agist_other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS rv_agist_prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS section_name VARCHAR(30) NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS section_seq_number SMALLINT NULL;
ALTER TABLE reporting.monthly_movements ADD COLUMN IF NOT EXISTS sub_section VARCHAR(30) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS feed_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS month_end_date DATE NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS other_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS prime_cost NUMERIC(12,4) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS rec_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS section_heading VARCHAR(30) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS section_name VARCHAR(30) NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS seq_no SMALLINT NULL;
ALTER TABLE reporting.monthly_reconciliation ADD COLUMN IF NOT EXISTS total_costs NUMERIC(12,4) NULL;
ALTER TABLE reporting.mrb_avg_supplier_years ADD COLUMN IF NOT EXISTS mrb_avg_yr1 REAL NULL;
ALTER TABLE reporting.mrb_avg_supplier_years ADD COLUMN IF NOT EXISTS mrb_avg_yr2 REAL NULL;
ALTER TABLE reporting.mrb_avg_supplier_years ADD COLUMN IF NOT EXISTS mrb_avg_yr3 REAL NULL;
ALTER TABLE reporting.mrb_avg_supplier_years ADD COLUMN IF NOT EXISTS mrb_avg_yr4 REAL NULL;
ALTER TABLE reporting.mrb_avg_supplier_years ADD COLUMN IF NOT EXISTS supplier VARCHAR(25) NULL;
ALTER TABLE reporting.soh_by_month ADD COLUMN IF NOT EXISTS head INTEGER NULL;
ALTER TABLE reporting.soh_by_month ADD COLUMN IF NOT EXISTS mnth_yyy_ymmm VARCHAR(10) NULL;
ALTER TABLE system.code_references_index ADD COLUMN IF NOT EXISTS database_table VARCHAR(40) NULL;
ALTER TABLE system.code_references_index ADD COLUMN IF NOT EXISTS field_name VARCHAR(30) NULL;
ALTER TABLE system.code_references_index ADD COLUMN IF NOT EXISTS lookup_table_name VARCHAR(25) NULL;
ALTER TABLE system.code_references_index ADD COLUMN IF NOT EXISTS lut_code_fieldname VARCHAR(25) NULL;
ALTER TABLE system.code_references_index ADD COLUMN IF NOT EXISTS lut_descriptive_fieldname VARCHAR(25) NULL;
ALTER TABLE system.database_flags ADD COLUMN IF NOT EXISTS pens_file_is_open CHAR(1) NULL;
ALTER TABLE system.error_log ADD COLUMN IF NOT EXISTS e_value SMALLINT NULL;
ALTER TABLE system.error_log ADD COLUMN IF NOT EXISTS error_code INTEGER NULL;
ALTER TABLE system.error_log ADD COLUMN IF NOT EXISTS mod_ule VARCHAR(100) NULL;
ALTER TABLE system.error_log ADD COLUMN IF NOT EXISTS proceedure_name VARCHAR(50) NULL;
ALTER TABLE system.error_log ADD COLUMN IF NOT EXISTS user_number SMALLINT NULL;
ALTER TABLE system.lookups ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE system.lookups ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE system.mmec_table ADD COLUMN IF NOT EXISTS bump_if_slick REAL NULL;
ALTER TABLE system.mmec_table ADD COLUMN IF NOT EXISTS dof INTEGER NULL;
ALTER TABLE system.mmec_table ADD COLUMN IF NOT EXISTS max_multiplier REAL NULL;
ALTER TABLE system.mmec_table ADD COLUMN IF NOT EXISTS target_multiplier REAL NULL;
ALTER TABLE system.rv_scheduled_dof ADD COLUMN IF NOT EXISTS dof SMALLINT;
ALTER TABLE system.system_info ADD COLUMN IF NOT EXISTS date_design_last_updated DATE NULL;
ALTER TABLE system.transaction_types ADD COLUMN IF NOT EXISTS trans_type_long VARCHAR(15);
ALTER TABLE system.transaction_types ADD COLUMN IF NOT EXISTS trans_type_short VARCHAR(1);
ALTER TABLE system.user_log_ons ADD COLUMN IF NOT EXISTS term_inal VARCHAR(50) NULL;
ALTER TABLE transport.datakey_truck_allocation ADD COLUMN IF NOT EXISTS allocate_to_datakey_number SMALLINT NULL;
ALTER TABLE transport.datakey_truck_allocation ADD COLUMN IF NOT EXISTS feed_cycle_no SMALLINT NULL;
ALTER TABLE transport.datakey_truck_allocation ADD COLUMN IF NOT EXISTS load_number SMALLINT NULL;
ALTER TABLE transport.datakey_truck_allocation ADD COLUMN IF NOT EXISTS ration_name VARCHAR(15) NULL;
ALTER TABLE transport.datakey_truck_allocation ADD COLUMN IF NOT EXISTS truck_load_weight REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS applied_to_feed_system BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS attachment TEXT NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS carrier VARCHAR(15) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS carrier_code INTEGER NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS contract_no VARCHAR(10) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS contract_value_per_ton NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS discount_value_per_ton NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS dm_pcnt REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS docket_number INTEGER;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS docket_time VARCHAR(5) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS docketnotes TEXT NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS drivername VARCHAR(15) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS exit_date DATE NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS exit_time VARCHAR(5) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS field_name VARCHAR(20) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS freight_cost NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS freight_per_ton NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS gross_wght REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS grower VARCHAR(15) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS invoice_paid BOOLEAN NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS load_rejected BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS load_value NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS moisture REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS no_of_bales REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS non_standard_commodity BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS payment_wght REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS prch_or_sale SMALLINT;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS protein REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS rcti_freight_invoice_done BOOLEAN NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS rcti_freight_invoice_paid BOOLEAN NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS risk_category SMALLINT NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS road_levy_per_ton NUMERIC(12,4) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS rtci_invoice_done BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS screenings REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS silo_used VARCHAR(10) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS staffid SMALLINT NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS tare_wght REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS test_wght_kgs REAL NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS vehicle_id VARCHAR(7) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS vendor_dec VARCHAR(15) NULL;
ALTER TABLE transport.deliverydockets ADD COLUMN IF NOT EXISTS weighunits BOOLEAN NULL;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS authorised_by VARCHAR(5) NULL;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS commodity_code SMALLINT NULL;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS docket_no INTEGER;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS notes TEXT NULL;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS rate_per_ton NUMERIC(12,4) NULL;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS reason_code SMALLINT;
ALTER TABLE transport.loaddockages ADD COLUMN IF NOT EXISTS tons REAL NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS eid VARCHAR(16) NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS new_animal BOOLEAN NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS program_id SMALLINT NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS sent_to_oracle BOOLEAN NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS sent_to_oracle_date TIMESTAMPTZ NULL;
ALTER TABLE transport.location_changes ADD COLUMN IF NOT EXISTS slaughtered BOOLEAN NULL;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS applied_to_storage_totals BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS comments VARCHAR(50) NULL;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS commodity VARCHAR(20);
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS delivery_docket_number VARCHAR(10) NULL;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS trans_date DATE;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS trans_tons REAL NULL;
ALTER TABLE transport.location_transactions ADD COLUMN IF NOT EXISTS trans_value NUMERIC(12,4) NULL;
ALTER TABLE transport.locations ADD COLUMN IF NOT EXISTS commodity VARCHAR(20) NULL;
ALTER TABLE transport.locations ADD COLUMN IF NOT EXISTS id SMALLINT;
ALTER TABLE transport.locations ADD COLUMN IF NOT EXISTS tons_stored REAL NULL;
ALTER TABLE transport.locations ADD COLUMN IF NOT EXISTS value_stored NUMERIC(12,4) NULL;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS from_location VARCHAR(20);
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS load_date DATE;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS manure_type VARCHAR(15) NULL;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS number_of_loads SMALLINT;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS operator VARCHAR(15) NULL;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS to_location VARCHAR(20);
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS tons_nett_weight REAL;
ALTER TABLE transport.manure_carting ADD COLUMN IF NOT EXISTS truck_name VARCHAR(10) NULL NULL;
ALTER TABLE transport.manure_locations ADD COLUMN IF NOT EXISTS from_location VARCHAR(20) NULL;
ALTER TABLE transport.manure_locations ADD COLUMN IF NOT EXISTS to_location VARCHAR(20) NULL;
ALTER TABLE transport.truck_load_variation_data ADD COLUMN IF NOT EXISTS actual_weight REAL NULL;
ALTER TABLE transport.truck_load_variation_data ADD COLUMN IF NOT EXISTS commodity_name VARCHAR(15) NULL;
ALTER TABLE transport.truck_load_variation_data ADD COLUMN IF NOT EXISTS target_weight REAL NULL;
ALTER TABLE transport.truck_load_variation_data ADD COLUMN IF NOT EXISTS truck_load_recid INTEGER NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS applied_to_cattle BOOLEAN DEFAULT FALSE;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS batch_number SMALLINT NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS batchbox VARCHAR(3) NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS driver_id SMALLINT NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS load_numb_for_day SMALLINT;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS load_recid INTEGER;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS load_time VARCHAR(5) NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS loader_id SMALLINT NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS ration_dm_pcnt REAL NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS staffid SMALLINT NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS target_load_weight REAL NULL;
ALTER TABLE transport.truck_loads ADD COLUMN IF NOT EXISTS truck_no VARCHAR(6);
ALTER TABLE transport.truck_names ADD COLUMN IF NOT EXISTS last_feedout_rec INTEGER NULL;
ALTER TABLE transport.truck_names ADD COLUMN IF NOT EXISTS last_loadout_rec INTEGER NULL;
ALTER TABLE transport.truck_names ADD COLUMN IF NOT EXISTS max_kgs_load_value INTEGER NULL;
ALTER TABLE transport.truck_names ADD COLUMN IF NOT EXISTS truck_number SMALLINT;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS comod_or_pen VARCHAR(2);
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS load_date DATE;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS load_number_for_day SMALLINT NULL;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS new_name VARCHAR(25) NULL;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS new_weight REAL NULL;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS old_name VARCHAR(25) NULL;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS old_weight REAL NULL;
ALTER TABLE transport.truckloadchangeslog ADD COLUMN IF NOT EXISTS truck_name VARCHAR(6) NULL;
ALTER TABLE transport.wbridgecomport ADD COLUMN IF NOT EXISTS baudrate VARCHAR(12) NULL;
ALTER TABLE transport.wbridgecomport ADD COLUMN IF NOT EXISTS comport VARCHAR(6) NULL;
ALTER TABLE transport.wbridgecomport ADD COLUMN IF NOT EXISTS scaletype VARCHAR(20) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS animal_welfare BOOLEAN NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS carrierid INTEGER NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS description VARCHAR(50) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS docket_date DATE NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS docket_time VARCHAR(8) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS docket_type INTEGER NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS docketid INTEGER;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS driver_name VARCHAR(30) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS exit_date DATE NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS exit_time VARCHAR(8) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS nvd_no VARCHAR(15) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS origin_destinationid INTEGER NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS purch_lot_no VARCHAR(15) NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS shrink_percent REAL NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS weighpersonid INTEGER NULL;
ALTER TABLE weighing.livestock_weighbridge_dockets ADD COLUMN IF NOT EXISTS weighunits BOOLEAN NULL;
ALTER TABLE weighing.weighing_events ADD COLUMN IF NOT EXISTS beastid INTEGER;
ALTER TABLE weighing.weighing_events ADD COLUMN IF NOT EXISTS last_modified_timestamp TIMESTAMPTZ NULL;
ALTER TABLE weighing.weighing_events ADD COLUMN IF NOT EXISTS timeweighed VARCHAR(8) NULL;
ALTER TABLE weighing.weighing_events ADD COLUMN IF NOT EXISTS weigh_note VARCHAR(20) NULL NULL;
ALTER TABLE weighing.weighing_types ADD COLUMN IF NOT EXISTS weighing_desc TEXT NULL;
ALTER TABLE weighing.weighing_types ADD COLUMN IF NOT EXISTS weighing_type VARCHAR(20);
ALTER TABLE weighing.weighing_types ADD COLUMN IF NOT EXISTS weighing_type_id SMALLINT;

-- Missing tables need full CREATE TABLE statements (see below)
-- TODO: CREATE TABLE feed.feed_totals_by_ration (...);
-- TODO: CREATE TABLE feed.pen_data_from_feed_db (...);
-- TODO: CREATE TABLE finance.custom_feed_charges (...);
-- TODO: CREATE TABLE finance.trading_costs_report (...);
-- TODO: CREATE TABLE health.chemical_inventory_old (...);
-- TODO: CREATE TABLE health.head_by_disease (...);
-- TODO: CREATE TABLE health.sick_by_dof (...);
-- TODO: CREATE TABLE pen.pen_mort_morb (...);
-- TODO: CREATE TABLE reporting.last_7_days_pulls (...);
-- TODO: CREATE TABLE reporting.monthly_rv_agist_reconciliation (...);
